" Dark background
set background=dark

" Don't want complete Vi compatibility
set nocompatible

" More powerful backspace
set backspace=indent,eol,start

" Mouse
set mouse=a

" Spelling
set spelllang=en_us

" Title
set title

" Set where to keep backups and swap files
set nobackup
"set backup
"set backupdir=~/.vim/backup
set directory=~/.vim/tmp

" Syntax
if &t_Co > 2 || has("gui_running")
  syntax on
endif

" Indenting
filetype plugin indent on

set autoindent
set smartindent
set nocindent

" Line numbers
set number

" Perl
"let perl_fold        = 1
"let perl_fold_blocks = 1

" PHP
let php_sql_query          = 1
let PHP_removeCRwhenUnix   = 1
let PHP_default_indenting  = 1
let php_show_semicolon     = 0
"let php_folding            = 2
"let php_parent_error_open  = 1
"let php_parent_error_close = 1

let g:debuggerPort = 9999

" Javascript
let javaScript_alternateSwitch = 1
"let javaScript_fold            = 1

" EJScript
au BufNewFile,BufRead *.es   setf ejscript
au BufNewFile,BufRead *.es   set filetype=ejscript

" JSON
au BufNewFile,BufRead *.json setf javascript
au BufNewFile,BufRead *.json set filetype=javascript

" Remark = *.rmk || *.rek
au BufNewFile,BufRead *.rmk  set filetype=remark
au BufNewFile,BufRead *.rek  set filetype=remark

" HTML Syntax Conversion Options
let html_use_css	= 1
let html_no_hyperlinks	= 1
let use_xhtml		= 1
let html_ignore_folding	= 1
if exists('html_no_pre')
	unlet html_no_pre
endif

" Folding
set foldmethod=indent
set foldcolumn=1
set foldlevel=1
set foldtext=MyFoldText()

" Position fold at indent
function! MyFoldText()
	let n = v:foldend - v:foldstart + 1
	let i = indent(v:foldstart)
	let istr = ''
	while i > 0
		let istr = istr . ' '
		let i = i - 1
	endwhile
	return istr . "+-" . v:folddashes . " " . n . " lines "
endfunction
