# history
HISTSIZE=2600
HISTFILE=~/.zsh_history
SAVEHIST=1800
setopt share_history appendhistory beep

# vim bindings
bindkey -v

# completion
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle :compinstall filename '/home/rummik/.zshrc'

autoload -Uz compinit
compinit

# woo-hoo! colors!
autoload colors
[[ $terminfo[colors] -ge 8 ]] && colors

# generate some color
function colorize {
	[[ $1 == 'rummik' ]] && print green && return

	n=0
	for i in $(sed 's/./ \0/g;' <<< $1); do 
		n=$(($n + $((#i))))
	done

	colors=(blue magenta cyan yellow white green)
	print ${colors[$((($n % 6) + 1))]}
}

# set PS1
PS1="%(!.%{$fg_bold[red]%}.%{$fg_bold[$(colorize $USER)]%})%n%{$fg_bold[black]%}@%{$fg_bold[$(colorize $HOST)]%}%m%{$fg_bold[black]%}"
PS1="$PS1:%{$fg_bold[black]%}%~ {%{$fg_bold[yellow]%}%h%{$fg_bold[black]%}}> %{$reset_color%}"

# terminal titile setting
precmd() {
	[[ -t 1 ]] || return
	case $TERM in
		sun-cmd) print -Pn "\e]l%n@%m: %~\e\\" ;;
		*xterm*|rxvt|(dt|k|E)term) print -Pn "\e]2;%n@%m: %~\a" ;;
		screen*) print -Pn "\e_%n@%m: %~\e\\" ;;
	esac
}

# include some bound keys from elsewhere
[[ ! $TMUX = '' && -e ~/.zshbindkeys ]] && source ~/.zshbindkeys

# path
export EDITOR="vim"
export BROWSER="/usr/bin/elinks"
export TZ='America/New_York'

# aliases
[[ `uname -s` = 'NetBSD' ]] || alias 'ls'='ls --color=auto'
alias ll='ls -l'
alias vi='vim'
alias emacs='echo'
alias links='elinks'

# load some other things
[[ -e ~/.zsharc ]] && source ~/.zsharc

# locale
export LANG=en_US.UTF-8
export LC_ALL=$LANG

# path
export PATH=$PATH:~/.bin

# tmux things
[[ -z $(tty | grep 'tty*') && ! $TERM = 'screen' && -z $(tmux ls 2>/dev/null | grep attached) ]] && (tmux attach || tmux)
