# history
HISTSIZE=2600
HISTFILE=~/.zsh_history
SAVEHIST=1800
setopt share_history appendhistory beep

# vim bindings
bindkey -v

# completion
zstyle ':completion:*' matcher-list 'm:{[:lower:]}={[:upper:]}'
zstyle :compinstall filename '/home/rummik/.zshrc'

autoload -Uz compinit
compinit

# woo-hoo! colors!
autoload colors
[[ $terminfo[colors] -ge 8 ]] && colors

# generate some color
function colorize {
	[[ $1 == 'rummik' ]] && print green && return

	n=0
	for i in $(sed 's/./ \0/g;' <<< $1); do 
		n=$(($n + $((#i))))
	done

	colors=(blue magenta cyan yellow white green)
	print ${colors[$((($n % 6) + 1))]}
}

# set PS1
PS1="%(!.%{$fg_bold[red]%}.%{$fg_bold[$(colorize $USER)]%})%n%{$fg_bold[black]%}@%{$fg_bold[$(colorize $HOST)]%}%m%{$fg_bold[black]%}"
PS1="$PS1:%{$fg_bold[black]%}%~ {%{$fg_bold[yellow]%}%h%{$fg_bold[black]%}}> %{$reset_color%}"

# terminal titile setting
precmd() {
	[[ -t 1 ]] || return
	case $TERM in
		sun-cmd) print -Pn "\e]l%n@%m: %~\e\\" ;;
		*xterm*|rxvt|(dt|k|E)term) print -Pn "\e]2;%n@%m: %~\a" ;;
		screen*) print -Pn "\e_%n@%m: %~\e\\" ;;
	esac
}

# include some bound keys from elsewhere
[[ ! $TMUX = '' && -e ~/.zshbindkeys ]] && source ~/.zshbindkeys

# path
export PATH="$PATH:$HOME/.bin:$HOME/bin:$HOME/source/android/bin"
export EDITOR="vim"
export BROWSER="/usr/bin/elinks"
export TZ='America/New_York'
export PERL5LIB="/home/$user/perl/share/perl/5.8.4/:/home/$user/perl/lib/perl/5.8.4/"

# aliases
[[ `uname -s` = 'NetBSD' ]] || alias 'ls'='ls --color=auto'
alias 'll'='ls -l'
alias 'vi'='vim'
alias 'emacs'='echo'
alias 'zblog'='~/source/zblog/zblog'
alias 'isup'='for j in {agnus.datazap.net,hope.datazap.net,faith.datazap.net,imagehostplus.com}; do if [[ ! -z $(curl -s $j | grep -i "<html") ]]; then print "[good] $j"; else print "[fail] $j"; fi done'
